name: Daily GeoIP and Geosite Compiler

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 02:00 UTC
  workflow_dispatch: # Manual trigger from UI

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write # Required to upload assets to Releases

    steps:
      - uses: Automodality/action-clean@v1
      - uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Go install v2fly/geoip tool
        run: |
          go install github.com/v2fly/geoip@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build custom geoip.dat files
        run: |
          geoip -c ./config.json

      - name: Generate sha256 checksums
        run: |
          sha256sum ./output/geoip.dat > ./output/geoip.dat.sha256sum

      - name: Upload and Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Daily automated build"
          body: "Automated daily compilation of GeoIP and not Geosite data."
          draft: false
          prerelease: false
          files: |
            ./output/geoip.dat
            ./output/geoip.dat.sha256sum
