name: Daily GeoIP and Geosite Compiler

on:
  schedule:
    - cron: '0 2 * * *' # Runs every day at 02:00 UTC
  workflow_dispatch: # Manual trigger from UI
  push:
    paths:
      - 'config.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 5

    steps:
      - uses: Automodality/action-clean@v1
      - uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: true

      - name: Go install v2fly/geoip tool
        run: go install github.com/v2fly/geoip@latest

      - name: Build custom geoip.dat files
        run: $(go env GOPATH)/bin/geoip -c ./config.json

      - name: Generate sha256 checksums
        run: |
          cd ./output
          sha256sum geoip.dat > geoip.dat.sha256sum

      - name: Upload and Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Daily automated build"
          body: "Automated daily compilation of GeoIP and not Geosite data."
          draft: false
          prerelease: false
          make_latest: true
          files: |
            ./output/geoip.dat
            ./output/geoip.dat.sha256sum

      - name: Workspace cleanup
        if: always()
        uses: Automodality/action-clean@v1
